package com.taulia;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rahul.joshi' at '11/9/15 10:30 AM' with Gradle 2.4
 *
 * @author rahul.joshi, @date 11/9/15 10:30 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
